ElMassimo/iles

docs/src/pages/config/plugins.mdx, packages/feed/README.md, packages/feed/package.json, packages/feed/src/feed.cjs, packages/feed/src/feed.ts, packages/feed/src/render-feed.ts, packages/feed/src/types.ts, packages/feed/tsup.config.ts, packages/iles/package.json, packages/iles/src/client/app/composables/vueRenderer.ts, packages/iles/src/node/index.ts, packages/package.json, playground/the-vue-point/components.d.ts, playground/the-vue-point/iles.config.ts, playground/the-vue-point/package.json, playground/the-vue-point/src/pages/feed.vue, pnpm-lock.yaml, pnpm-workspace.yaml
[îles]: https://github.com/ElMassimo/iles
[routing]: https://iles-docs.netlify.app/guide/routing
[feed]: https://github.com/jpmonette/feed
This pull request adds a new `@islands/feed` module, which provides:
- 📻 supports RSS, Atom, and JSON feeds
- ⚡️ HMR during development to debug the result
- 💪🏼 type autocompletion, powered by [`feed`][feed]
=> feat: create @islands/feed module to generate RSS, Atom, and JSON feeds

packages/iles/src/client/app/index.ts, packages/iles/src/node/config.ts, packages/iles/src/node/plugin/plugin.ts, packages/iles/tests/not-found.spec.ts
This pull request makes the internal not found page the default in development instead of showing a user-provided 404.
Previously, the internal not found page was only used if the user did not provide a `404` page, simulating the behavior of the deployed site (most service providers will use `/404.html` if available).
In practice, it's more helpful to see an explicit message when this happens in development, the user-provided `404` can be tested by navigating to it directly instead.
=> feat: use internal not found page during development as it's more helpful

packages/iles/src/node/build/bundle.ts
This pull request fix a bug where iles fails to build when the project has a package.json file with its type set to `module`. See the [reproduction repository](https://github.com/titouanmathis/iles-esm-cjs-conflict-reproduction) for an example.
This was happening because the files in the temporary directory are in CJS with the `.js` extension. When the root package.json type is set to `module`, files in CJS format should have a `.cjs` extension.
I tried several fixes bundling iles to ESM with `tsup` but it is not as simple as changing the format in the `tsup.config.ts` file and iles should detect the type of project to work correctly.
The simplest fix is adding a package.json file in the temporary directory with the type set to `commonjs`.
With `"type": "module"` in the root …
=> fix: `ERR_REQUIRE_ESM` error when project type is set to `module`

docs/src/pages/config/index.mdx
This pull request fixes the type shown in the docs for the `siteUrl` config option.
This was happening because the `siteUrl` config option seemed to have the type from the `jsx` option.
By changing type to `string` and removing the default, it matches the actual type: https://github.com/ElMassimo/iles/blob/main/packages/iles/types/shared.d.ts#L201
=> Fix type for siteUrl config option

docs/src/components/TheSidebar.vue, docs/src/pages/config/index.mdx, docs/src/pages/guide/markdown.mdx, packages/feed/src/feed.ts, packages/iles/src/node/config.ts, packages/iles/src/node/plugin/documents.ts, packages/iles/types/shared.d.ts, packages/mdx/src/mdx.ts
This pull request adds support for _unpublished_ documents, which is useful to commit work in progress.
You can mark an individual document as _unpublished_ by using `draft: true`.
```mdx
---
title: Still not ready
draft: true
---
```
By default, draft pages and documents will be displayed in development, but will be excluded when building the site. Use the <kbd>drafts</kbd> setting in `iles.config.ts` to override this behavior.
=> feat: add built-in support for drafts in pages and documents

packages/iles/src/client/index.ts
This pull request fixes the type checking in [my îles project](https://github.com/johannschopplich/zahnarzt-schopplich.de).
This was happening because of the following TS error:
```
node_modules/.pnpm/iles@0.7.37/node_modules/iles/dist/client/index.ts:11:26 - error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
11 export { useVueRenderer, VueRenderable } from './app/composables/vueRenderer'
~~~~~~~~~~~~~
Found 1 error in node_modules/.pnpm/iles@0.7.37/node_modules/iles/dist/client/index.ts:11
```
By adding an explicit type export, the type checking should be fine.
None available.
=> fix: explicitly export types from composable

.npmrc, README.md, docs/src/pages/guide/index.mdx, docs/src/pages/guide/plugins.mdx, package.json, pnpm-lock.yaml
Updated some commands according to the latest default pnpm version
Now v7 is the default version of pnpm
- `pnpm init` is no longer an alias for `pnpm create`, it will create a `package.json` instead of using `create-*`
- `pnpx` is now just an alias for pnpm dlx, and `pnpm <cli>` is equivalent to `pnpm exec <cli>`
- If `peerDependencies` is missing, the dependencies will not be installed successfully
=> docs: update command according to pnpm v7

package.json
update pnpm filter pattern
In pnpm v6, in order to pick packages under a certain directory, the following filter was used: --filter=./apps
In pnpm v7, a glob should be used: --filter=./apps/**
This is an addition to #117. I accidentally forgot about it.
=> chore: update pnpm filter pattern

docs/src/pages/guide/pwa.mdx
The link for `ReloadPrompt`  on PWA docs is wrong
This was happening because the link is worng
By changing the `pwa.mdx` adding `src` on the link
no
=> docs(pwa): fix `ReloadPrompt` link

packages/iles/src/node/build/islands.ts
As discussed in https://github.com/ElMassimo/iles/issues/130
This was happening because islands weren't building to outDir
By addin`outDir: config.outDir` to vite config in island build
=> fix: outDir in islands build

packages/iles/src/client/app/composables/appConfig.ts, packages/iles/src/client/app/composables/islandDefinitions.ts, packages/iles/src/client/app/composables/reactivity.ts, packages/iles/src/client/index.ts
This pull request changes some regular imports to type imports to solve #138.
Refer to #138 for the cause of the issue.
By changing regular imports to type imports we can prevent TS from calling them out as errors and unblock the builds.
=> Use type imports for imports not used as values

packages/hydration/vue.ts
This pull request extends `@islands/hydration` to name Vue Island Apps after their root component.
It uses `import.meta.env.DEV` so it has no impact in the compiled bundle.
=> feat: display nice app name for islands in vue devtools (closes #140)

docs/iles.config.ts, docs/src/pages/guide/pwa.mdx, packages/pwa/package.json, packages/pwa/src/pwa.ts, pnpm-lock.yaml
This PR uses `workbox ManifestTransform` when pwa is configured via `@islands/pwa` plugin/module: this way we can control the sw precache manifest, adding or removing entries.
Also includes the configuration based on `prettyUrls` on `workbox.navigateFallback` entry: will use the `Vite base` or `/` when not configured.
If the pwa plugin is configured via `Vite` instead using `@islands/pwa` plugin/module, using `prettyUrls: false` will produce an error on runtime when registering the sw, since it will have the html entries twice in the sw precache manifest: you have a comment about  not adding the `addRoutes` entries on line 195 (the comment is about `prettyUrls: true`, since we'll end with the html file and also the route name, but registering the sw will work).
**TODO**: 
- the …
=> feat: use `ManifestTransform` when using `@islands/pwa`

packages/hydration/vue.ts, packages/iles/src/client/app/composables/vueRenderer.ts, packages/iles/src/client/app/index.ts
This pull request enables more efficient hydration by using `createSSRApp`. See: https://vuejs.org/guide/scaling-up/ssr.html#client-hydration
`createSSRApp` is optimized for hydration of SSR-rendered HTML. This is more efficient because if the HTML stays the same, only event listeners need to be applied but the DOM is left untouched.
By using `createSSRApp` we get all the benefits of efficient hydration.
=> fix: use createSSRApp to enable more efficient hydration

packages/hydration/vue.ts, packages/iles/src/client/app/composables/vueRenderer.ts, packages/iles/src/client/app/index.ts
Reverts ElMassimo/iles#156
@maoberlehner The proposed PR suffers from the same problems I mentioned in https://github.com/ElMassimo/iles/issues/149#issuecomment-1180889417.
Happy to revisit this later on, but for now I haven't found a way for the final build not to have hydration mismatches in the docs site.
[Removing the comments Vue injects](https://github.com/ElMassimo/iles/compare/fix/create-ssr-app#diff-552f9fbde284e784909452eb7dc4cfd8fbcb2b35111cd9e35c9a3f7667ebd48dR38) fixes the hydration mismatches in development.
The following screenshots were taken by running a full `build:all` in https://github.com/ElMassimo/iles/commit/49d4d9a2a26dd7662f9ae552e5a8c809512e96d1, with the precaution of disabling the PWA and unregistering all service workers, to ensure I was testing the right …
=> revert "fix: use createSSRApp to enable more efficient hydration"

packages/headings/src/headings.ts
This resolves #154.
A counter is used to track the number of duplicated titles.
To pass the counter to the slug generator, the API of `generateSlug` is modified.
ids are taken into account when generating distinct slugs, but duplicated ids are not resolved and kept as-is, because it's the user's responsibility to not set duplicated ids.
An example (test suite):
title     id      slug
foo       none    foo
bar       none    bar-2
foo       none    foo-2
foo       bar     bar
foo-2     none    foo-2-2
foo-4     none    foo-4
foo       none    foo-3
foo       none    foo-5
bar       none    bar-3
foo-2     none    foo-2-3
foo-2-2   none    foo-2-2-2
foo       bar     bar
A consideration is that the type and initialization of `counter` limit the freedom of `HeadingOptions.slug`. Maybe we can …
=> fix: prevent duplicated slugs for headings with the same title

packages/images/src/images.ts
This pull request fixes an incorrect `typeof` check in the images module, which broke esm/cjs compatibility.
=> fix: esm/cjs incompatibility in images module

packages/iles/src/node/build/render.ts
This pull request fixes the Windows incompatibility issue reported in #161.
This was happening because unlike require, the dynamic `import` in node does not handle forward slashes in Windows.
By prepending the path with the `file://` protocol, it interprets the path correctly.
Thanks to @ohuu for providing detailed information and proposing a solution ❤️
=> fix: windows incompatibility when rendering site (close #161)

docs/src/pages/guide/documents.mdx, packages/excerpt/README.md
This pull request changes the documentation to drop the deprecated `import.meta.globEager` (since Vite 3) usage. 
This was happening because Vite 3 was released.
Not really a fix, just a documentation update.
=> docs: deprecate `import.meta.globEager` usage

packages/iles/src/node/build/utils.ts
This fixes #167.
#167
Decode the resolved path in the file name, but keep `%2F` (`/`) encoded.
=> fix: do not encode file names of dynamic routes

packages/iles/src/node/build/chunks.ts
when your product includes a . in the directory name, for example `codepunkt.de`, chunk matching for vendor modules doesn't work properly due to the module id being split at `.` and reading the second element of the resulting array, meaning to read the file extension, but instead reading an arbitrary part of the path after the `.` in the project (and/or other directory) name.
this fixes that by using `lastIndexOf` to correctly asses the extension.
This pull request fixes a bug
This was happening because finding out the extension when calculating the vendor chunks wasn't done properly
By changing to `lastIndexOf`, this works.
=> fix: vendor chunk categorization

package.json
Use the stricter glob pattern wrapped in single quotes.
When people use pnpm's [`shell-emulator`](https://pnpm.io/cli/run#shell-emulator), shell will not recognize a glob pattern that is not strict enough.
Because it will be processed by the shell-emulator first.
```sh
~/Desktop/iles chore/pnpm
❯ pnpm dev
> root@ dev /Users/kecrily/Desktop/iles
> pnpm -r --parallel --filter ./packages/** run dev
 ELIFECYCLE  Command failed with exit code -7.
```
=> chore: strict glob pattern in internal scripts

packages/iles/src/client/app/components/Island.vue
Fix `Island.vue` component got error framework.
`props.importFrom` will be the absolute path of component. If the username may contain '.', `Island.vue` component will get error framework.
Always get the ext from the end of filename
=> fix: get ext from the end of the file name

packages/headings/src/headings.ts
This pull request prevents heading slugs from being "app".
If the slug of a heading is "app", it will conflict with the id of the main `<div>`.
Another possible fix is to use a different id for the main `<div>`, which is less likely to be a heading, but that could possibly be a breaking change.
By adding "app" in the initial counter for heading slugs.
=> fix: prevent heading slugs from being "app"

packages/images/src/images.ts
The id looks like `composables/mdxComponents.js?v=a217f6bd` since around Vite v3.1.
This caused all images to be corrupted in dev mode.
Use `includes` instead of `endsWith` to check the `id`.
But I'm wondering why not use a remark plugin instead of the Vite plugin 🤔 (I haven't tried writing a remark plugin for `<Picture>` yet, maybe it simply doesn't work for some reason.)
=> fix: rendering MDX images in development

packages/iles/package.json, packages/iles/src/node/build/render.ts, pnpm-lock.yaml
This pull request adds support for body tags by updating the page template in `renderPage()` and fixes #191 by @harlan-zw.
`@vueuse/head` added support for tags at the `bodyClose` position. But the version used in the project didn't have that feature.
By updating the `@vueuse/head` version to the latest, and updating the page template to render `bodyTags` generated by that package, we can add support for tags placed at the end of the page.
=> feat: update version of @vueuse/head

packages/iles/src/node/build/write.ts, packages/iles/src/node/plugin/plugin.ts, packages/mdx/src/mdx-vite-plugins.ts
This pull request fixes all uses of `String.prototype.replace` where the second argument is a string expression containing variables, by using functions that return these expressions instead.
This fixes #224.
https://stackoverflow.com/questions/28102491/javascript-better-way-to-escape-dollar-signs-in-the-string-used-by-string-prot
=> fix: use functions instead of variables for String.prototype.replace

packages/feed/package.json
Fixes #230 by @dhruvkb
This was happening because the version of `iles` pinned in the dependencies is older than the current version `0.9.x`.
By relaxing this pinning, we can allow the package to be installed in projects using the latest version of îles.
=> fix: relax @islands/feed pinned version of îles

packages/prism/README.md
This pull request fixes the CSS snippet for displaying language in the code preview generated by the `@islands/prism` plugin.
The included code snippet did not work because
- the language `div` needs to be relatively positioned
- the `::before` pseudo-element needs two colons
By adding `position: relative` and the missing colon, these problems can be fixed.
=> Fix style for displaying language in Prism
